# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11a3bc6b9780d4dbe3ae37662228d369ddffe72414b0e6f7adbc97e8fb6141a394272ea4b1a28ddc545c94fec46629998bee4512002d5a2ff638cd9f18cb0a7b

test:
  secret_key_base: 77dff6335318f5c1c881e00a874819f2eb3d1050dfe6a550db3c9bb1519d858c8b7be7cf695d62e70312ba7b2c410c0de187067178577175130b99c1a2aa353a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 3d518b0a95458ec02318755e27d47a89a01ae54b31af6393a93179bda4ff8a1da5e11bd9b3cb10d6009e9e12592872ab5521c97af52a924a5cf744b10c1b77f4
